version: "3.7"

services:
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  blab_db:
    build: ./db
    restart: always
    volumes:
      - blab-db-data:/var/lib/postgresql/data
  api:
    labels:
      traefik.port: 80
      traefik.frontend.rule: "PathPrefixStrip:/api; Host:localhost"
      traefik.backend: "api"
    build:
      context: ./api
      target: ${MODE}
      args:
        - mode=${MODE}
    volumes:
      - ./api:/go/src/api
    restart: always
  client:
    labels:
      traefik.frontend.rule: "Host:localhost"
    image: vtcs2304s19/blabber-client
  tests:
    image: vtcs2304s19/blabber-api-tests
    environment:
      SERVICE_NAME: api
    restart: "always"


volumes:
  blab-db-data:
