version: "3.7"

services:
  app:
    build: .
    restart: always
    ports:
      - 80:80
  blab_db:
    image: postgres:alpine
    restart: always
    volumes:
      - blab-db-data:/var/lib/postgresql/data

volumes:
  blab-db-data:
