version: "3.7"

services:
  reverse-proxy:
    deploy:
      labels:
        traefik.docker.network: "traefik"
      placement:
        constraints:
          - node.role == manager
    image: traefik
    command: >
      --api
      --docker
      --docker.swarmMode
      --docker.watch
      --docker.exposedByDefault=true
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - host
      - traefik
  blab_db:
    image: cabellwg/blabber-db
    deploy:
      labels:
        traefik.port: 5432
        traefik.backend: "db"
        traefik.docker.network: "traefik"
    volumes:
      - blab-db-data:/var/lib/postgresql/data
    networks:
      - traefik
  api:
    image: cabellwg/blabber-api
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: "PathPrefixStrip:/api; Host:api.docker.localhost"
        traefik.backend: "api"
        traefik.docker.network: "traefik"
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - traefik
  client:
    image: vtcs2304s19/blabber-client
    deploy:
      labels:
        traefik.port: 80
        traefik.docker.network: "traefik"
        traefik.frontend.rule: "PathPrefix:/; Host:client.docker.localhost"
      replicas: 2
    networks:
      - traefik

volumes:
  blab-db-data:

networks:
  traefik:
