version: "3.7"

services:
  reverse-proxy:
    deploy:
      placement:
        constraints:
          - node.role == manager
    image: traefik
    command: >
      --api
      --docker
      --docker.swarmMode
      --docker.watch
      --docker.exposedByDefault=true
    ports:
      - 80:80
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  blab_db:
    deploy:
      labels:
        traefik.port: 5432
        traefik.backend: "db"
    image: cabellwg/blabber-db
    volumes:
      - blab-db-data:/var/lib/postgresql/data
  api:
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: "PathPrefixStrip:/api; Host:front.docker.localhost"
        traefik.backend: "api"
      replicas: 2
      restart_policy:
        condition: on-failure
    image: cabellwg/blabber-api
  client:
    deploy:
      labels:
        traefik.port: 80
        traefik.frontend.rule: "PathPrefix:/; Host:front.docker.localhost"
      replicas: 2
    image: vtcs2304s19/blabber-client


volumes:
  blab-db-data:
