version: "3.7"

services:
  reverse-proxy:
    image: traefik
    command: --api --docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  blab_db:
    build: ./db
    restart: always
    volumes:
      - blab-db-data:/var/lib/postgresql/data
  api:
    build:
      context: ./api
      target: ${MODE}
      args:
        - mode=${MODE}
    volumes:
      - ./api:/go/src/api
    restart: always
    ports:
      - 5000:5000
  client:
    image: vtcs2304s19/blabber-client


volumes:
  blab-db-data:
